name: Update

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths-ignore: ['README.md']
  schedule:
  - cron: '23 1 * * 1' # Monday at 1:23 AM

permissions:
  id-token: write # Enable OIDC
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - uses: google-github-actions/auth@v0
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - uses: google-github-actions/setup-gcloud@v0.6.0
      with:
        project_id: jason-chainguard

    - name: Update
      run: |
        # The first time it's run, bq poops out a bunch of setup stuff to
        # stdout, which we don't want in our CSV, so we dry-run the query
        # to hopefully get that out of the way.
        cat query.txt | bq query --dry_run=true --nouse_legacy_sql --max_rows=1

        ./update.sh

        set +e

        # If licenses.csv.gz has changed, commit it.
        if git diff-index HEAD | grep licenses.csv.gz$; then
          # Delete creds before they're committed to the repo.
          rm gha-creds*.json || true

          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Update: ${timestamp}" || exit 0
          git push
        else
          echo "No changes to licenses; no commit needed"
        fi

